spring:
  data:
    mongodb:
      user: sgbd
      password: admin
      uri: mongodb+srv://sgbd:admin@sgbd.zg5c1.mongodb.net/Server?retryWrites=true&w=majority

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 3600000

mail:
  host: smtp.gmail.com
  port: 587
  username: example@gmail.com
  password: password
  protocol: smtp
  tls: true
  properties.mail.smtp:
    auth: true
    starttls.enable: true
    ssl.trust: stmp.gmail.com

